apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ${BUILD_REPOSITORY_NAME}-database
  namespace: ${NAMESPACE}
  labels:
    service: database
spec:
  serviceName: ${BUILD_REPOSITORY_NAME}-database
  selector:
    matchLabels:
      service: database
  replicas: 1
  template:
    metadata:
      labels:
        service: database
    spec:
      containers:
        - image: postgres:14-alpine
          name: database
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: postgresql
              mountPath: /var/lib/postgresql/data
              subPath: postgresql
          envFrom:
            - secretRef:
                name: ${BUILD_REPOSITORY_NAME}-database-secret
  # Volume Claim
  volumeClaimTemplates:
    - metadata:
        name: ${BUILD_REPOSITORY_NAME}-postgresql
        labels:
          app: ${BUILD_REPOSITORY_NAME}
          service: database
      spec:
        accessModes: ['ReadWriteOnce']
        resources:
          requests:
            storage: 10Gi
