apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: city-gallery-strapi-database-secret
  namespace: standalone
spec:
  encryptedData:
    DATABASE_PASSWORD: AgAK+97MAtVJyQMiEoa5X4Ak+VW8pXZGH9vx96SmoWFNpQIXj8W3AsshKodBN/KlVbZb/cRyk4BGFpVZbDPMxkvK+mHyEDgGIl7GPQm9lM7CuUATgECtQp8M+lDrk/3BuAHlHf7Sgy+ElNl1H3foTnyVPZMfxuuymM2cNzK+R4OXvZlyMfgAwBdZtty+Rnux2ZJJg/2e4hX+lbI4VkBpt9mzu8/ZqFvqV+nc1uRD4b0IuRv/9OAhhBot/NgNQq5iCw9c2MbbMzXRkJQtoDARI1p4HOphV/nHXE7rT4ef9gt6anfBKGNwMfCIBJKDOA4CY047iw3t1s/jAYPkN6Phyi8Wz+NGZ7Amxy83e79QIi/WLYUuzwDcP0te+clV4DhV+A7ArRiUIKWsybgm11PQnfz/4jh7khzGe8uqJQgTpp7wCB+l//r6XOHrGMVS6I5lsEgNzC30jWR4xQikLDXd9BRZ7qUx1/vB1TtWzxV2vRfFB4jjh5d6qz0Mz3OikhkDT4r1xXa9e1bwdK5qEq5IBADBTmn480eCMTbg+PsscPQGUP5Eqe7OlgvTRU+8e7Hk+Az0i7qBoJo07hHwKiSZx0C0Ay+BNxnzkqkvhVEbsvqjiksQVFghNrLmYNZfUEnT650xk3Zg2pUmSzESB/Yn+RoQ2R6bmTVQ9JwIunUcDN0e4XJwT2AZmJBf/yw3wSAWJo8kuvoas6Oit69DKR1sJOCW67k5D/X+AuWxewflNHV8y/pqLBT5fl8KU9XHSsavD8E=
    POSTGRES_PASSWORD: AgC4tbzJ2vtm97XrPhXff38Npp8ucamziiubW3dPnjYJQvzZlYZtFVmQcQDEa1Y5tI7gK9sZkHNf8/owHXLkKZsFcR0Jks6jFEV/RwCz3kasgkYxFU0qpfQ86nkXPU21Z/ruELY/h7Ehju2McaOwIvcaTHjV3Ohej4oktuKooly6A3yBQU+XnZt3iPkOJLyhvaGyr4Qv5B8HAk5bfKRyaggvMSYGB8DAc9iFeMjBgs6U19HU8cy8rw7dnfdI7OT/hSR38JusnO0n26gl68uJZKTbR7Wal3vclVTWdUa8E3dLpBDxEzLHQOlxI+SlmV9W9/zO0gOVpnn0z9qIx4+cTL64K/t9QtLYq6o414MBGdEdC+6PRfaLuxHpqzUPRUzY1SupAVMx8vkmvcyXINM47Vx8mDijAb064UrcBfbCBkiD7/KO/UvcPlsrPFj/ttXOSZHRp+iLBnBUGLoo3FqFhO02HoTq1zbcLXtneZub73e4A0ehK7IKFFO5jpIorq8tFKOKm4q3Wa9oQP1mNGzAGrKp6HIY1DwnnGx1E73lY/FnlSpISCUv6midIJ7et7QXIVf8PQSwbiL7XexO6/07zDlXcANFXkk51l0ZaokD83ivBv1DE/RNjKapBLCkk6NYsiema1WI2ojsz7yjZL7meGhNTRYoqv2sB7Tza847xytvFlkGCkCb9qpea6GxRspGEw/S5uebeQa2aSGufvLX+5I62KfYfyRQA4sNRMIQzkv+WJjj2QY6hm9GTO1ix2gcdE0=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: city-gallery-strapi-database-secret
      namespace: standalone

