apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: city-gallery-strapi-database-secret
  namespace: standalone
spec:
  encryptedData:
    DATABASE_PASSWORD: AgCEvPW8H2/tysyXL/tvk/0BvB0Dm/3uNXJVlnUk3t3KfcJo84XXG5ygsVmjzEM6N9ztpM8g/u9cIVM14vQ+IVYF/jikMm2eyoi6+ZkEePigmzAtZ92ZrD5IUmFgrvxpQgTUnjbhGnUIZIoZqhsGattO5vrsOZWkjxNnEKfQUaMbhv8/FiIWewwncdLPlcxcFEu9hZTzR02YcrITfKQqP2mJy3MTc3gxY9fqacZV44jHTrdIC4GixeqnejGRUO+Fa5C+xVsH9ctG/yj1TFWnAeb1IdPvsIc1+rQcyPUgGcrJNo/ieh1slZx9dU0aTN5YdEKSouWHA1p9dgQUWV4u6uCvcfwlNjmQ+FE3ziK6oK9VHus3Iq3vtCE6fgvDIqPzo3O4mSPbYTmI3jMJiql9j/03lbiFkxnzMaDhjPHyi+GQZuLRLGjplKlR1jft7UovsmN+wCJ7bBxu0Q4O0rVzZqF3VLyQkxuW6c3mEQjelbOxNC91ntvS6bfBZk+4LPbszByUro7MehcSEJsBmmQAV/JUURtRXm3SBx5/sRfesWoc+Bi1yVkePQWBqpQsQBNPJ/D0THYDpUZoc2XOvvyk39aTsclIpSlLk2I6MssGPOK+OznsbZ4iFbiem2dvgeYhAAUPcdFCEw8x284tjYvKuaHr2klyWTAKp03xJEbuGzQf/fJ/+dzTRxy/wH9heLZ9hutlDTHOgQsIUnXDjnyEe1EF42vCX5wihk/sPlhTh5cCbF5g33IWmulu/UUcpjg=
    POSTGRES_PASSWORD: AgBqM81iHdKwcwi4ymOLyNispl2sTcHHNeHlDtbL35rBSJygx7QjSiejYIdFi6cnuojQ0D/Kw0qJarBFA3ylf0Qk2iUT8XBR02rRVl4SjaotZEjMRFfIvuq70skYygsXYn2jGayroXF+J6XJooLBwo5cm5w/Q4i/+apiFoFs6b7cgAVI60qllsG9Tblf5ZUs9mJl3Rbllc1b9wntDpO5PZz+SkaFNjK2hwVU1cm92wLeT2GbkFkCYyKwOgxs/tM8VDUkX0C57DmsfjKpwiCUQ7lX/qjkzgo1e01IqSW96Sn4zRhcdd8JhIrGt7SdVAl8S++5BxmjmFY3iyXQjKJcKvN8zFDXs7hiz8IeRNuz5rmY6qbUhZgyhRmsr921mauMKHgTtvf3FRCbhhlqwlYNuHxR+aWnBs2ygNLjK2SIkmdvqaiTYi/jL7cP6SJZZHLf7Xun/Ac+QBISC29crjWZBUBN1z7QmlGqE9XQ2d2l2LbxJHF0OGBz3/dybSJRf9Gym4F34DJWM6Asd8QBAqY3bHWGDFcXBvQbTlzwJbi9sAMXYLQ5S4R3mtEU2Ga6wd4nKGPQnZt4kuaQPkhpdb3h0aHf91O6zSLN8rqnKfCTeEf4qaYL0AG9tXjchOJKLDpTP+2WRAjp+C+KSytvp1fYopyZV12iyU3NQV9I1hZuOcj4EQqszWPPgDh/qddEfHxdiRt8sugjKYJ1BW6AZxJuoY8fy0umGR8gEUXea7IJDE4//+ZSyqdUu4XChLgAzaw=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: city-gallery-strapi-database-secret
      namespace: standalone

