apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: city-gallery-strapi-meilisearch-secret
  namespace: standalone
spec:
  encryptedData:
    MEILI_MASTER_KEY: AgCNdlihAdW1B/YLaw0uJh6y9xX7xTsqlEfQaNY4NU8+YGA9NLz3waHjD9L8P5dvnSKlGn1P6SDPI8gxTlrxD9czYdrSuw7IQbOuKm1lL5zw10kIrX1sV95GNFB+5J2uYBymt026yBVaALO5UvBHxSmQC/DP0Kx66sJAGJNq15YEoJmWQp2+/om7wgTLX63Fcap5HrzcBy16uWo2tPsjlnALCzEH9EzDBXpjkT21HjbTMvg3xTdQQIO2cNXPYbXJYUh0SlSyUXX5PFlHbsBon+l+Xv891EC9Im4h4teauHtl1/MGsPnHv7Fvy5K+f646biqfENAcpNvqbE4AzorjYLL3LLPy8iT8PzkMk7VyJ19D/1jb/x6Ce4KnzRl4aRZbwx0NTKIhl9ixtk189PB/NS9iINtWrFGOilPylynA1iZVRbxkVTlfa0WYdeOxBQMp+jsBdokpSUL4Au8AdWchML+/aDCL5w9LyBl2M2Myc1TOIUCbmkh4Tx0wQaHwr95QnfyCuGizgG5y5LY3HUfys3vPsemViw8+nG52zyzBynZFYKg1xiGJ9xw4Wrvn39y/PXwUd7Ytq7haHaUW/owlgpIpIhPGQzPm7e0Sp2vqoAH4kxVS4xxvE9P3k4osFOhKLlMfNmWvigMhVc+bU7urqsRIWr2HAkbir19WA2EvpoUGe/sBNgnyfmV035vrlifZhAzLz2QiKg+kquc8CC5XtG4hLhCq2xQoQnJx6Nc2cGGl+DzNJK8khx1M9iknGzQrVwdfntRylP6XUQA=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: city-gallery-strapi-meilisearch-secret
      namespace: standalone

