apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: city-gallery-strapi-meilisearch-secret
  namespace: standalone
spec:
  encryptedData:
    MEILI_MASTER_KEY: AgBl6O5feDaBAP7e4FuFaHv4qikPItYIyXne9RLMr30+DN1ZdH97ZS9xvk+xn3P9iXQQCmpfW6C+LQmruR6HBWKzGZEunblazQY6xf7aO2PMNYtV2ey2d7VCVP8zITc2Urj8exr5pkgN6/6zSoV+8bSDaJIV7wqVlDvc5FQ1Hc5SJl/83joQ6rkOS8Tauu8ySawY7eHNkREY+nFRWW6l7qtn9FLbkWQdi6MIA2AKZTzNKCCOjoMZtCSr4ZM+k+Wx8WeUJXXo7Zt0fRxypB/rL18zdqx0mxzy9qEwUROw9Fkp9/vnWCtTtGEq2gzfjEJmVnISpEwCxKgqsQJZIgd+fmIQggBFPrb/sJwBlfW6ka4Z0GhYsZ2oe6NwMNFiI5bgAXtJqhSfxhukV5vp0/I1TtDNV6p3Z2Tx6oBn+ZcQwwLRI+YyccxuMNsBc2nIVwLhQdwuy2SK3fyY9sn+r00+3Q9WEfykDX7QsUZDa25DXrfVE5b2KDyouSRdWj2Rybu9dhP0j8m+NW/bHp8fOrbkb0Dr2I3o3PFqWmbTJyqyIqI13iiJvThto60z/WrQ8aBvyOAr7OGox6oAQoeu0wlgnncFtcFdEKu7Lurzzp5eYnamkZ3ovFynJsvWdtqKA/ficSGHvqaFGl/WyTnjrVEjc9qomgneSC4/7kPN3Bt0CKQNUA+ztrVDEiA2EOskZPmXJj4204mIHfRePP5frDwdUqhXmqEL1O7e0RGYK/zDEtYLR8Kbd/sPNjC2MqEagt/XWVAF6JwahB4peg==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: city-gallery-strapi-meilisearch-secret
      namespace: standalone

