apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: city-gallery-strapi-meilisearch-secret
  namespace: standalone
spec:
  encryptedData:
    MEILI_MASTER_KEY: AgAfA0sEClwQngLfBi8DJq0REsE34OiGjAQZldZSGfY0V4t+xyl/vLb3nUMPeH8u6UrMI4WLeOW1BXuOFe7CpSZf1LEkZtV5cv3MYRl8eXYOlwcCApN/YXKqeUL5ULSF4LPVAI8S3Ven0/Xfg3JDB2d4n22POG3tWdWpWKKwLyG9gPrJLobNrILCEVQ3brnrS9w2Uiz7+Obkc69lAKMwSxFpAmRnKY0ehLakWqMazYDJBNzFDlCy+4T+WjS+zWBRc4/OAy+Z8VVM+anYyBcpl+8Jd4gufRVO6oTWOqg/1BprdJrKvHavwNMu3m2+dnzmjJK1ibUMl5Ja5ZEw2WQB0FeAWeEutKLxAjwt0IeVaVmod5JrPVbfWGam9/VJ+LXcw7CUDYL6fJSR5E/kilkjHL+8Kbne62GnnACU7YlhmVf8c6Fljd6JSaWW6GyGN3feiGA5ocY58WEyPOye2fjLDarRB4hUqQXUfNsLj2b6qzp3MKipluY0EvndQ8o0RIdeXD6A4UDVIOJdwG9NEjOKhADDUvwC2GKlorTqbtiNiB0JBAMelBwvQcJfLs/KZpSoboN7z6614TBLvOXFp3neEkVlBlxha+wFt91H/I7uonx1I84wWM04pAPsiWzLAK3oprXfsPqk7f2J5WK3XwdGcJwWJ5UAT1rpL1DXT7ChWWyXGbGbespC4f0IixqJHzfASf2QSGdREZwa0z7vnABmpGhx12509UhMOoC8+RaiDKQg80LV+PjJAbPHcb1ObFWSXfa/9nJz43HBQ2ug56IgARzCBJKjVXQ=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: city-gallery-strapi-meilisearch-secret
      namespace: standalone

