apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: city-gallery-next-general-secret
  namespace: standalone
spec:
  encryptedData:
    REVALIDATE_SECRET_TOKEN: AgC571p7StMpNPwn48a4OOsILu4/Dby8g9xNCCWHJ1xcNIHW0M85vnW3ILQX2SeM38971YTPyTM1aLSj3VhATOX4KCItOpnTg5Up4FY0ESABAPs637QaXYbx+0ZoUGkYtsl/2yV96US2NyNaNz57AF7xHuI6jihX5QXCNt3dowGV/UYxC1qO45EQ1x7maqasiv3w17XmXC/j9n0micNO1EzALSK5lvqCxFo2qvgQ7+AyiICZ+0HuBT06hkK03mqZDG/R7nHE9LB9xaNTmqvzBDchttDywZqtoNZZLwLlhJVRp2L9NRcqLLdYskmNrgF+iI5ay1aKADyVWt76jhpMgYhw74TUmp2MUI7dYvQT96iaBq0uQxY/VGm4bHSo1MMi8lJJh/+C84rhf6Z72NoMYihXsxnp5l6fk7r/nEfZ6ZVJXXFPgTBgpeWRr1LfDzwiq8vJfbywCBPc+lZPjS820sA/1p/dIZVquoPPzyNAjxpJLWJM6UBT92MGEId4Fnzv5YwuesOMvQDAL/iLQur1w//EWomEvuWtW/5ofehFYvcGJM9dvddZKB4smdLZBZssuPFWvdd50he+ZNMmfVmq+f8pogRfGAD+PKcETt5+/470Euw73zNrJeZ4aWnDMV2zW+kCgSo6yhhxT9A3/2iPiHq2+US1T7FJEU1jlmkYJeT5UtFkXgTPgJy/Q1+meOglSF/Hd0IQwxTCxbNo7Jt+as7E1+OA5GSKFrIO4KtQQFwj
    STRAPI_PREVIEW_SECRET: AgBdcWrbjgn+y1hK8qyUhKE2SlokJnPqP8scBt/HNWdMFlOZp4X0uIiT0FZGW47Ra8ZQ0sy+YjuSt52Af4VAZyVc2/xccoQI7wWn0+LOoxR5ADpzPy5h6b1j2yrEkrThzd1KfkZIlMG7eo11DLozn2jsdzxvcAvOiCfUOjvwP9dDCjcnEmVn3lqvYO26nAo7QE3UPjeauTqdlVA7DPbjBeU2wB3VQrCVrp/udrRlEqro+Bfzx6WIAewj72axbSG+n5ZzEJqNkm+6CBH3vNIahUA1uEfxG4yLX3YPHmz3lOMeO8EfI1yO2TwpBnVVc/SJyUdVXRJuPUYYGNQ8kgTXVeKbsC73moNP+u3ZiiMlv5vnb7qwubUC63UgUuB6RlbFAmDj8+dm3V+7Rcq/xnkvidPEUppgyFVgJEQgC1Xa0WBvrzFz0pkbaUPhq4sBsQX5297aA9k9VsNYORgUopwDOkpaN3PAbi69o9WdPg9mC8+pvWK74P+31M7npBBaVKWLGZ40/Ll6doPLxPk+6N9IQhGSUkHokrrdbviekkknvoiKDczsKSV1YD4iJofLYna5ktJijYOJ8bGk+G/tvlORTfdXflw3URvkh431BXpGwItGAmxt0MRwl4dkDxkldPNFXaCy/lWImrKYBRXKUKZq90jlTvBN0y8ClORhi/ECEjmiT97lKSr+tAHLwKKHEcuo5vTwXJFE7IfSCnBVcTADPMffoGfnYuOEtlU=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: city-gallery-next-general-secret
      namespace: standalone

