on:
  workflow_call:
    inputs:
      directory:
        description: 'A Folder within the repository where deployment should be called'
        default: '/'
        required: false
        type: string
      registry:
        description: 'Registry where should be built images stored'
        default: 'harbor.bratislava.sk'
        required: false
        type: string
      namespace:
        description: 'Namespace where should be build app deployed'
        default: 'standalone'
        required: false
        type: string
      cluster:
        description: 'Kubernetes cluster name'
        default: 'tkg-innov-dev'
        required: true
        type: string
      url:
        description: 'Kubernetes cluster url'
        default: 'https://tkg.dev.bratislava.sk'
        required: true
        type: string
      username:
        description: 'Docker username'
        default: 'robot$github_actions'
        required: false
        type: string

    secrets:
      registry-pass:
        description: 'Password for registry where docker is uploading images'
        required: true
        
      service-account:
        # kubectl get secret <service account secret> -n=standalone -o jsonpath='{.data.token}' | base64 --decode  > token.tmp
        description: 'Kubernetes service account'
        required: true

jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.directory }}
    steps:
      - name: Checking out
        uses: actions/checkout@v3

      - name: Directory check
        run: pwd

      - name: Install Prerequisites -  Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Installing Bratiska-cli
        run: yarn global add bratislava/bratiska-cli

      - name: Running git fetch for Bratiska-cli
        run: git fetch

      - name: Kubectl tool installer
        uses: Azure/setup-kubectl@v2.1

      - name: Kubernetes set service account token
        run: kubectl config set-credentials default --token=${{ secrets.service-account }}

      - name: Kubernetes set server with certificate account token
        run: kubectl config set-cluster ${{ inputs.cluster }}  --insecure-skip-tls-verify --server=${{ inputs.url }}

      - name: Kubernetes set context cluster
        run: kubectl config set-context ${{ inputs.cluster }} --cluster=${{ inputs.cluster }} --user=default

      - name: Kubernetes use context
        run: kubectl config use-context ${{ inputs.cluster }}

      - name: Login to Harbor
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.username }}
          password: ${{ secrets.registry-pass }}

      - name: Print Bratiska-cli version
        run: bratiska-cli deploy --version

      - name: Running build and deploy with Bratiska-cli
        run: bratiska-cli deploy --namespace=${{ inputs.namespace }}
        continue-on-error: false

